### ISSUE TITLE
Hashids organization maintanance

### ISSUE THREAD

**Issue by tzvetkoff** [hashids/hashids.github.io#55]
Hi all @hashids/owners,

Since Ivan apparently quit GitHub some time ago (the current account with the name `ivanakimov` is obviously not him) our "organization" future is at question.

I'd like to ask a few things:

1. Should we keep the same group of maintainers?  We're pretty occupied all of us and none of us has enough time to do all the stuff but at least we can keep the site intact.
2. Who owns the domain hashids.org?  If we're what's left as maintainers and none of us holds its rights, shouldn't we switch to another domain before it expires? (2020-05-11)
3. "The _bright_ future?" - any had any thoughts of 2.0?

**Comment by tzvetkoff** [comment]
I also ask this question to count up who's active so we can keep forward and actually remove or update non-working/non-maintained ports - there are at least 3 issues for that that I'd like to get rid of.

**Comment by ullmark** [comment]
Oh, that's odd!

re. activeness. I've been patching the .net version as much as I've had time, when bugs comes in. Been very busy lately and no one seem to want to be a collaborator so it's not like I do daily updates ;-) 

Current feeling re. 2.0, I don't think I will be starting a rewrite any time soon, but I'd gladly hand over the reigns if someone wants to maintain the library. I've had _(according to nuget.org)_ 757 126 downloads so someone probably wants it to be updated?

**Comment by dswitzer** [comment]
I haven't updated the ColdFusion version of the library in a while, but there haven't been any issues either—which is why I haven't made changes. :) That said, I'm not sure anyone is using it either...

**Comment by tmorehouse** [comment]
I haven't made any changes to the SQL version... not am I sure if anyone is using it.

**Comment by speps** [comment]
The Go version hasn't had many issues, I'm maintaining it as much as I can whenever issues come up. I have no statistics, it's used by 50 other public packages according to pkg.go.dev but I don't know how much use those packages have.

Most important point there is getting the domain I think, I thought the public face of hashids was always pretty good. However, I would go away with .org as it's been controversial recently.

I don't care that much about evolving hashids, I think the algorithm is fine as it is.

**Comment by peterhellberg** [comment]
I’ve been making minor changes to [hashids.rb](https://github.com/peterhellberg/hashids.rb) once in a while, not actively coding in Ruby these days since Go has stolen my heart since many years :)

**Comment by jd327** [comment]
Hi all,

Ivan here. @tzvetkoff, thanks for bringing up the issues. To answer your questions:

1. Yes, it'd be nice to keep the same group (with the option of inviting new active contributors). I made all of you admins so you're not blocked on anything and can continue to have discussions (as you are here!) and make proper code changes. It's a small library, so once the code is written, maintainers are not always active so I'd generally lean towards leaving people as maintainers, unless you all believe that either the code or the dev is hurting the community in some way (which I have yet to see). If the library or addon is clearly outdated or not working and the owner is MIA, it's probably safe to remove the link from the website.

2. I do. I've just renewed the domain till 2029, and can continue doing that. If someone would like ownership of the domain and the community would like me to transfer, I'm more than happy to do that.

3. I'm open to discussing the future and v2. If there's demand for it, we can start a wiki and/or separate issues to see what could be improved.

And a few thoughts in general:

- I didn't quit Github, but I did become less visible. I'm sorry, I wasn't aware this might cause a bit of a stir, which is why I guess I'm addressing it here. Even though I am not as active as I used to be, I'm still lurking in the back (as you can see), and if someone is ever blocked by me, please let me or this org know.

- I've also had two ports of Hashids (in [JavaScript](https://github.com/niieani/hashids.js) and [PHP](https://github.com/vinkla/hashids)) and handed them off to active developers that know these two languages better than me, so I'm confident those particular ports are in good hands.

- Finally, governance of open-source projects is of course not a simple manner, but I believe that I (or any one person) am not needed to be at the top in order to make decisions or have progress. I've only created two ports initially and all the amazing devs in this group have created 30+ implementations, without me ever asking anyone. I'm forever grateful for all the decentralized work this community continues to do, and in the odd few cases where my input is needed, I'm happy to chime in.

**Comment by alco** [comment]
Hi all. I'm the author of [hashids-elixir](https://github.com/alco/hashids-elixir). It hasn't been updated for a year because there wasn't a need - the library is working fine and, judging by the [download stats](https://hex.pm/packages/hashids) of Elixir's package manager, it's actively used. It saw 5k downloads in the last 7 days.

**Comment by laserpants** [comment]
Hi everyone. The [Haskell version](https://github.com/laserpants/hashids-haskell) is also still being maintained although not that many changes, apart from occasional bug fixes and a few contributions from the community via PRs.

**Comment by zakame** [comment]
Hi, I maintain the [Hashids.pm](https://metacpan.org/pod/Hashids) (Perl 5) version.  Aside from a small bugfix release last month, there hasn't been much change in its code for years, but I still keep my two eyes on it :)

I'm definitely in for any v2/future updates, and I think this org here seems to be the right place for such discussion and work. :muscle:

**Comment by jovanpn** [comment]
Hi all. [hashids.as](https://github.com/jovanpn/hashids.as) hasn't have any issues or bugs to be fixed since first release so I don't know if it is used any much. Anyway, because Flash Player died, this library remains here only for AIR developers but I'm also in for any v2/future updates.

**Comment by tzvetkoff** [comment]
@jd327 Hey, I didn't know you changed usernames.  I guess this resolves this issue/question then.
I'll say lets keep things as they are at the moment and just cleanup stale/non-working ports then.

**Comment by fanweixiao** [comment]
Hi all, I maintain the [hashids-java](https://github.com/10cella/hashids-java) version with @0x3333 and there hasn't been much change in its code for years. Some users, proposal to see the v2.0 release.

**Comment by 0x3333** [comment]
Java version, as @fanweixiao said, is quite stable and no development has been made since Oct 2018. There is a proposal for 2.0, but it is related to a more idiomatic java than features per itself.

**Comment by leprosus** [comment]
Hi, I'm the author of [Kotlin version](https://github.com/leprosus/kotlin-hashids) it is still supported but the code changes quite a bit. Never the less I keep making fixes and handle PRs
